### PR TITLE
Run darwin setActive in a separate thread to avoid jank

### PR DESCRIPTION
**Pull request by jointhejourney**
Hey there,

Currently, the `AVAudioSession setActive` method gets called on the main thread and it causes dropped frames / jank.

This is a simple update to avoid this this type of jank.

Here's a similar issue on StackOverflow: https://stackoverflow.com/questions/18419249/ios-audiosessionsetactive-blocking-main-thread

Thanks for the great package!

### CODE REVIEW

**Comment by jointhejourney** [comment]
@ryanheise plz let me know if I need to update anything else to merge this in. Thanks!

**Comment by jointhejourney** [comment]
Hey @ryanheise any chance we could merge this in?

**Comment by ryanheise** [comment]
Hi @jointhejourney , first of all thank you for the PR. I am just working on pushing out the next releases of just_audio and audio_service first and then I will be able to review your PR.

**Comment by ryanheise** [comment]
I've just pushed out those releases. This PR is next on my list.

**Comment by ryanheise** [comment]
This is now published in 0.1.19. Thanks for your contribution!

**Pull request merged**
