### PR TITLE
Update build.gradle minSdkVersion 23

### PR DESCRIPTION
**Pull request by Asadq518**

### CODE REVIEW

**Comment by Asadq518** [comment]
update your sdk version

**Comment by ryanheise** [comment]
Can you explain this change? In general, `minSdkVersion` should be set as low as possible. Are you saying this plugin can't support sdk level 16? (If so, what is the specific reason?)

**Comment by ryanheise** [comment]
Hmm, now your latest commit increases the "min" sdk version even higher, first 16, then 23, now 28? I don't think that can be justified.

**Comment by Asadq518** [comment]
It looks like the issue is related to the minimum SDK version required by the audio_session package. The error is indicating that a specific method (getAddress()) in the AndroidAudioManager.java file requires API level 28

kindly resolve these issue

**Comment by ryanheise** [comment]
That call is guarded by checking `Build.VERSION.SDK_INT` within the code, so perhaps this is happening due to newer build tools. Can you let me know what version of everything you're using including gradle?

**Comment by Asadq518** [comment]
now i m using
compileSdkVersion 34
minSdkVersion 23

ext.kotlin_version = '1.7.10'
classpath 'com.android.tools.build:gradle:7.2.0'

just_audio: ^0.9.33
audio_session: ^0.1.16

Dart SDK version: 3.0.6
Flutter 3.10.6

**Comment by ryanheise** [comment]
Ah, audio_session doesn't yet support `compileSdkVersion 34` (See the second most recent issue: #108) So for now you  will either need to compile with a lower sdk or wait for a proper fix (or use your own workaround).

**Comment by Asadq518** [comment]
/Users/apple/.pub-cache/hosted/pub.dev/audio_session-0.1.6/android/src/main/java/com/ryanheise/audio_session/AndroidAudioManager.java:271: Error: Call requires API level 23 (current min is 16): android.media.AudioDeviceInfo#getId [NewApi]
                "id", device.getId(),
 

`compileSdkVersion 33`

but still same issue

**Comment by ryanheise** [comment]
Closing since `minSdkVersion` should be set as low as possible.

**Pull request closed without merging**
